spring.application.name=PaTrackPleaseBackend

# Supabase PostgreSQL (SSL required)
spring.datasource.url=jdbc:postgresql://db.kntikcuouojbjehlapms.supabase.co:5432/postgres?
spring.datasource.username=postgres.kntikcuouojbjehlapms
spring.datasource.password=a7CTVvQJvEGgBhPL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

